version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - dev.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django
    ports:
      - "8000:8000"